### ISSUE TITLE
Loading and Unloading .tox files

### ISSUE THREAD

**Issue by OrdinaireX** [medcelerate/FFGLTouchEngine#11]
Hey this a bit of a feature request, 

but it would be great to have an unload button that would unload the .tox files from VRAM. As it is now, the TouchEngine instances stay in VRAM to load in the background. They unload from VRAM if you delete the TouchEngine source in Resolume, but it would be much more convenient to be able to close their instance as needed.

Thanks so much,

O.X

**Comment by medcelerate** [comment]
This should be easy to do, the instance will stay hot for fast load times though. It may require a button to unload the engine itself in addition to unloading the tox. In future versions there my be an option to do bluegreen style loading with multiple instances living hot for swapping between toxs faster.
