### ISSUE TITLE
Pixel Format: 32-bit float RGBA

### ISSUE THREAD

**Issue by OrdinaireX** [medcelerate/FFGLTouchEngine#12]
Hey I found an issue with some of my .tox files where they give a black screen if the pixel format is 32-bit float RGBA. If I swap them back to 'use input' then they work fine. You can see this in the example I shared before. if you go to the GLSL top at the bottom layer of this .tox, and change the pixel format, then it will work.

https://drive.google.com/file/d/1obgDypTAbzRD_J5WlNGPaHPEqEvt66SW/view?usp=drive_link 

I had some similar issues in my previous setup when sending video over Spout I could never replicate, just thought I'd share this experience here.

**Comment by medcelerate** [comment]
Ah yes this makes sense as the interop used to move textures between
systems is currently limited to 8bit on the input. In the future there will
be a way to check this and scale however it may not have much impact as I
think resolume runs only in 8 bit maybe.
