### ISSUE TITLE
Heading Parameter causing Issues

### ISSUE THREAD

**Issue by OrdinaireX** [medcelerate/FFGLTouchEngine#13]
Hey I use Header Parameters for a few different things in my .tox files, but when being loaded through the plugin they cause the others to not appear in Resolume.

I also have some suspicions with XY parameters causing problems. I'm currently deleting them altogether but having them either appear or be ignored and working in the background could add some helpful functionality.

Cheers!

O.X

**Comment by medcelerate** [comment]
Can you try the latest version and if it is not fixed provide me a tox file
