### ISSUE TITLE
Framerate Issues when Previewing .toxs and stutters when loading

### ISSUE THREAD

**Issue by OrdinaireX** [medcelerate/FFGLTouchEngine#16]
Hey first I just want to say love the new update, seems to work well and will help a lot with stability.

I noticed when viewing 2 instances of TouchEngine at the same time in Resolume, either by layering or by previewing, it really affects the framerate a lot, regardless of the complexity of the .tox file. Even when loading two very lightweight .tox files, it seems to slowdown quite a bit. 

I imagine people will be wanting to queue up their .tox files before showing them off, so this combined with that classic TouchDesigner stutter when loading, and then the preview framerate dip can be disruptive.

From my own experiences making .tox based solutions to VJing with Touch, I know that this is likely a tricky issue to solve, just wanted to document it.

Great work with the latest build again. Thanks!

**Comment by medcelerate** [comment]
I saw this issue and it was due to network errors caused by a bug in TouchDesigner. Please updated to the latest version of TD 2023 release and this issue will be rectified.
