### ISSUE TITLE
absTime.seconds too fast

### ISSUE THREAD

**Issue by function-store** [medcelerate/FFGLTouchEngine#17]
Hi, first of all thanks a lot for developing this much needed integration!

I just dropped a simple test of a noise texture transformed with `absTime.seconds` and it moves way faster than in TD. I also output the value in a Text TOP and it is indeed running around 2 times faster

**Comment by medcelerate** [comment]
Hmm, my only assumption could be that resolume is calling the cook function faster than the intended frame rate. This is a bit odd as I haven't encountered this issue and the seconds should be tied to the system clock and not resolume

**Comment by function-store** [comment]
it is a vanilla Resolume install with default settings on a Win11 machine

**Comment by medcelerate** [comment]
What version of TD are you on. We have noticed issues with older 2023 builds. The latest TD 2023 release is working the best.

**Comment by function-store** [comment]
It was at the time latest 17700. I'll be testing with 18880 soon

**Comment by function-store** [comment]
I believe I found the reason @medcelerate !

In your code you're initializing everything with 60 frames. I set my output monitor (which used to be on 144Hz) to 60, and now things seem to be running normal speed. 

Seems like there could be a solution provided in your code directly, but for knowing this already helps.

**Comment by medcelerate** [comment]
Interesting, it may actually have to do with the d3d device and how it
clocks. The solution would be to set frame rate based of ffgl but I’m not
very sure how to do that.
