### ISSUE TITLE
SOP File leads to crash

### ISSUE THREAD

**Issue by fasoric** [medcelerate/FFGLTouchEngine#18]
Hey there, thanks for this total gamechanger, you are doing an amazing job!

I spotted a little bug: when you have some _external_ geos (even .tog) into your tox, the plugin doesn't work, but it does with the default ones.
I already found a workaround which is placing the geos in the td samples folder (C:\ProgramFiles\Derivative\TouchDesigner\Samples\Geo), so i guess it's an easy bug to fix :)

keep up with the hard work and thanks for open sourcing it!

**Comment by medcelerate** [comment]
I may be able to prevent a crash if this is causing a crash but this may be
better noted on the touchengine GitHub from touchdesigner

**Comment by medcelerate** [comment]
Closing as this may be better served in the touchengine-windows repo.
