### ISSUE TITLE
Lost Performance with Notch Blocks

### ISSUE THREAD

**Issue by jacobvnsn** [medcelerate/FFGLTouchEngine#2]
First off, thank you thank you thank you for putting this together!!!
Initially i had Blocks running in Tox files at 60FPS immediately after installing the plugin. Then after about 10 minutes my framerate dropped to about 45fps. In TD the blocks run at 60 FPS consistently, I've tried restarting my machine, restarting Resolume, creating a new Resolume composition, etc. They all begin running at 45FPS after all of those troubleshooting attempts. The only thing i haven't tried yet is reinstalling the plugin. I don't think it's my system throttling due to heat based on the resource usage in Task Manager, along with the fact that it runs steady at 60 FPS in TD.

**Comment by yannicksengstock** [comment]
This must be a complex issue that might not be solvable within the plugin itself. To clarify, restarting your PC is the only troubleshooting step here that significantly impacts the function of the plugin. There's no impact on the plugin's functionality from changing the composition or reinstalling the plugin
