### ISSUE TITLE
Struggle with high resolution

### ISSUE THREAD

**Issue by Lindaannanic-AVHS** [medcelerate/FFGLTouchEngine#21]
Hey, thanks again for this great plugin. Unfortunately I am usually dealing with a resolution of ~16k to 1k and then it stops working. With this resolution it usually just remains completely blank, sometimes not even loading the parameters, but with the most simple example tox i worked my way up to a black canvas. The error message I get from resolume sometimes (but not the last times) was constantly: "_FFGL: Failed to create interop_".
I am using Touchdesigner version 2023.11600 with educational license and licensed resolume version 7.17.3. 
Here is a link to the projects and toxes: 
https://drive.google.com/drive/folders/14vDnhmOha9E2KCWaJ_oqW3xUL2YCIux0?usp=sharing
(I know this is quite an unusual request, so I would also be happy to buy you more coffee for this, just reach out to me at Kofi)

[](![Screenshot_Resolume](https://github.com/user-attachments/assets/6a5c52ff-5a7e-4ec4-9789-1207c4e63866))

**Comment by medcelerate** [comment]
Ok this is what I suspected it could be, I believe this may be to a texture size limitation in the interop library I am using. I will test and report back with what I find.

**Comment by medcelerate** [comment]
Hello, so I believe this issue may be with touch engine, I am seeing the texture access being returned as true but the texture is null. I would put an issue in the touchengine-win repo.

**Comment by Lindaannanic-AVHS** [comment]
Ok thanks for much for your help, i put an issue out and will keep you posted :)

**Comment by medcelerate** [comment]
Feel free to reopen this issue if you find it isn't resolved from the derivative end.
