### ISSUE TITLE
Only first two parameters work in Arena

### ISSUE THREAD

**Issue by kylepingeon** [medcelerate/FFGLTouchEngine#22]
Arena v7.13.2 rev17774
Touchdesigner 2023.11880

Floats and integers work fine, but I can't get booleans, strings, or switches to work.  I tried using the example file: InputOutput5Param.tox as well as my own tox.

**Comment by kylepingeon** [comment]
Okay so actually the problem is only the first 2 parameters function for me.  Any parameters lower in the list do not work in Arena.

**Comment by medcelerate** [comment]
Hello I believe this has been fixed in https://github.com/medcelerate/FFGLTouchEngine/commit/b607696cc0650d6360b3cd51fd27f956a18a6a03

**Comment by medcelerate** [comment]
Check beta2

**Comment by medcelerate** [comment]
Closing due to no updates.

**Comment by kylepingeon** [comment]
This is resolved.  Thanks!
