### ISSUE TITLE
Regressions in v1.0-beta

### ISSUE THREAD

**Issue by vacuumn** [medcelerate/FFGLTouchEngine#23]
Hi there, Evan.

Thank you for the work, awesome tech. 

When running latest version I am encountering instabilities and most parameters not working. Also the performance dopped in comparison with previous version. 

OS: Win11 (10.0.22631 Build 22631)
Touch: 2023.11880
Resolume Arena: 7.21.3
GPU: Nvidia RTX 3070, Driver: 551.61

There are 3 main problems

### **1. Parameters**
Non-functioning parameters as others already reported. 
Floats and ints only occasionally working, without any obvious pattern. 
Boolean fields mostly working, 

### **2. Instabilities**
Loaded source TOX can turn black after few seconds of working fine. 
"Clear Instance" and "Unload" followed by "Reload" will usually result in tox not reloaded or loaded but black screen.

### 3. Performance

Attaching source TOX. It is producing **60** fps in Touch without any issues. 
With v1.0-beta it goes below **40** fps.

[2DFractal_out1.zip](https://github.com/user-attachments/files/16647322/2DFractal_out1.zip)

**Comment by medcelerate** [comment]
Thank you for your input. I have gone ahead and fixed the issues with parameters (https://github.com/medcelerate/FFGLTouchEngine/commit/b607696cc0650d6360b3cd51fd27f956a18a6a03). I am running on a 2070 super and see your tox running at 60. Check for the next release that will be generated momentarily.
