### ISSUE TITLE
Min/Max/Default Par not working properly

### ISSUE THREAD

**Issue by tattoovabien** [medcelerate/FFGLTouchEngine#24]
Hi, 
First of all, thank you for making this tool! It will change my life for sure :)

I'm having a few small issues though with the TouchEngine: 

Float: doesn't show the default and can only go from 0 to 1 (while min is 0, max is at 360 and default at 150)
Int: doesn't show the default but can go infinite.
Str: Works properly
Menu: Works properly

attached you'll find a zipfile with the tox inside: 
[project4.zip](https://github.com/user-attachments/files/17288593/project4.zip)

I updated Touchdesigner but that didn't seem to be the issue, but so I have the latest version. 
<img width="415" alt="image" src="https://github.com/user-attachments/assets/811ebc25-a99a-4bb5-b744-9270b0453394">
I'm running windows 11 and NVIDIA GeForce RTX 3070 Laptop GPU
<img width="209" alt="image" src="https://github.com/user-attachments/assets/a69b2655-7c53-4441-bae5-b99b445dc8be">
I'm running Resolume 7.16.0
<img width="102" alt="image" src="https://github.com/user-attachments/assets/c4adc25d-5481-444c-9029-7463bd612737">
I have the Pluginfolder referenced in my resolume settings
<img width="306" alt="image" src="https://github.com/user-attachments/assets/ade132b4-f7ab-401f-8d7b-614c0a10f74f">
I have the dll's like this: 
(before I had them not in a folder but just in the main plugin folder and that didn't seem to change anything)
<img width="640" alt="image" src="https://github.com/user-attachments/assets/45b6c9a2-da52-4952-9812-45631d56d23f">

Thanks for taking your time to read this :) 
Cheers! 
Lucas

**Comment by medcelerate** [comment]
So float will only range between 0 and 1 due to limitations in ffgl, I am considering auto scaling these values under the hood but can have a look.

I'll have a look at in, but this is for the most part the same as float unfortunately.

**Comment by tattoovabien** [comment]
Thank you for your response. 
Alright, luckily there's enough ways in Touch to work around it :) 
One more thing is that when connecting the parameters from touchengine in resolume to the dashboard knobs, the names appear as 'parameter 1', 'parameter 2',... 
My setup is really focussed on these dashboard knobs and seeing the names of the parameters would be a big help. Do you know a way I could work around this? :)

**Comment by phattiej** [comment]
Hi, I didn't want to open a new issue, but I have similar question/request.

When I create a parameter in TD as "pulse" action, the action shows up in Resolume TouchEngine as a checkbox that I have to check on and off, is there anyway to make it into just a button?

:)

![Screenshot 2024-10-13 000547](https://github.com/user-attachments/assets/2184649c-0d84-43c9-aa25-b5c183f307a4)
![Screenshot 2024-10-13 000608](https://github.com/user-attachments/assets/f661d694-0ca8-42f4-a4e9-9dcb0bd99546)

**Comment by medcelerate** [comment]
> Hi, I didn't want to open a new issue, but I have similar question/request.
> 
> When I create a parameter in TD as "pulse" action, the action shows up in Resolume TouchEngine as a checkbox that I have to check on and off, is there anyway to make it into just a button?
> 
> :)
> 
> ![Screenshot 2024-10-13 000547](https://private-user-images.githubusercontent.com/90050121/375990352-2184649c-0d84-43c9-aa25-b5c183f307a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5OTA0NDIsIm5iZiI6MTczMDk5MDE0MiwicGF0aCI6Ii85MDA1MDEyMS8zNzU5OTAzNTItMjE4NDY0OWMtMGQ4NC00M2M5LWFhMjUtYjVjMTgzZjMwN2E0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDE0MzU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmOGMxOGYwYjBjMDY3M2MyNmFlYTY3ZjU1NTcxYTM1N2MwOWUzZDY1MTA5ZWY2ZTMyYzI0MGIzOTg3OWFjYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.C58D9DijJ8kiVGrFCHTcTmBJaDIuNYDILmMbBEiUtCk) ![Screenshot 2024-10-13 000608](https://private-user-images.githubusercontent.com/90050121/375990354-f661d694-0ca8-42f4-a4e9-9dcb0bd99546.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5OTA0NDIsIm5iZiI6MTczMDk5MDE0MiwicGF0aCI6Ii85MDA1MDEyMS8zNzU5OTAzNTQtZjY2MWQ2OTQtMGNhOC00MmY0LWE0ZTktOWRjYjBiZDk5NTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDE0MzU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5NDU5NGJjNmNmYzhhOWFlMDdjMzdkM2NhZDU5Y2E3N2YyNTIwNTcyYThmMGE0YmUwZTIyMTVjZGExYTk0MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pTi1tabJl1QUv5Hr7edvQ1zAtc4AjVZM0g1WBEnlkHM)

Interesting, yes pulse should definitely be a momentary. I'll look to see what is the source of the bug.

**Comment by medcelerate** [comment]
I've gone ahead and fixed pulse so it is a momentary now. At the moment setting default values is limited, please open a request with the reoslume ffgl repo to request the addition of the feature.

**Comment by drmbt** [comment]
https://github.com/resolume/ffgl/issues/15 I'm assuming this is your reference on the range limitations with FFGL? 

Auto ranging and changing the label would make this much easier for porting a body of TD plugins to resolume, is that on the roadmap?

**Comment by medcelerate** [comment]
Floats are always this case unfortunately an integers have a suitable range
however, this happens during the construction phase of the plug-in so
unfortunately due to FFGL limitations I can’t make dynamic ranges

**Comment by drmbt** [comment]
but you could remap and relable under the hood, as described in that issue, no?

**Comment by drmbt** [comment]
in this issue Joris describe this here https://github.com/resolume/ffgl/issues/52
