### ISSUE TITLE
Avenue/Arena crashes when loading TouchEngine source

### ISSUE THREAD

**Issue by Bigpig131** [medcelerate/FFGLTouchEngine#26]
Howdy! I've been trying to get the TouchEngine plugin working but my instance of arena or avenue crashes before I can actually use it. I have the 3 plugins in a directory that resolume can see, and the source/effect show up in my browser. I can load the source into a clip slot, but once I click the slot to have it showing on that layer, resolume starts to go real slow then freezes and crashes.
Am I doing something really wrong here? Lol I've tried reinstalling my resolume, tried reinstalling the plugins but still can't get it to work. Any insight or advice would be super appreciated and i can provide any other details if needed. Thank you!

**Comment by medcelerate** [comment]
Can you please provide your resolume log file here so I can see what is happening?

**Comment by Bigpig131** [comment]
[Resolume Avenue log.txt](https://github.com/user-attachments/files/17691328/Resolume.Avenue.log.txt)
Hi thanks for getting back to me, this is the log from avenue, I'm using trial version if that is of any relevance. Maybe I just have the .dll files in the wrong place? But the plugin does load, and the example NoiseOutOnly.tox shows for a split second before it all freezes. If you need any other info just let me know, thanks again!

**Comment by medcelerate** [comment]
Unfortunately, your log doens't show much other than loading touch engine. I would try to update your touchdesigner version to the latest version and see if that rectifies the issue. Also if you have any touchdesigner logs you can send that would be helpful.

**Comment by Bigpig131** [comment]
Thanks for checking it out, yeah I thought it didn't reveal much but figured there might have been something I'm not smart enough to spot 😅 although I have been very dumb with this, I haven't updated TD since march this year (need a new commercial license) so I'll try with the latest free version and see if that plays nice with your plugin. Thanks again for looking into it!

**Comment by medcelerate** [comment]
So the free version won’t work with the plugin unfortunately

**Comment by Bigpig131** [comment]
Makes sense, I'll get back to it once I have relevant Resolume and TD licenses lol. Much appreciated, thank you very much

**Comment by medcelerate** [comment]
Closing for now
