### ISSUE TITLE
Project doesn't build due to glew dependency

### ISSUE THREAD

**Issue by t3kt** [medcelerate/FFGLTouchEngine#4]
When I try to build the solution, I get an error about `GL/glew.h` not being found. There's a comment near that that says to include `{root}/deps/glew.props`, but that file doesn't appear to exist in the repository at least in its current form.
Am I missing something?

Alternatively, are there binary builds available somewhere? The readme says that they'll be in releases but there don't appear to be any releases.

**Comment by medcelerate** [comment]
You do not need glew.props to build, and releases will be available eventually. There were a number of changes to the repository last night however the glew library is included

**Comment by medcelerate** [comment]
Releases are now available, building is also portable.
