### ISSUE TITLE
TEVideoInputD3D undeclared identifier

### ISSUE THREAD

**Issue by phattiej** [medcelerate/FFGLTouchEngine#5]
When I build the solution I am getting the error message that TEVideoInputD3D is an undeclared identifier in TouchEngineFX.cpp, when I open TouchEngineFX.h file the identifers were commented out. But when I un-commented them out it created 100 more issues when I built it again.

However, when I opened the plugin in resolume, it seems to show my toxes custom parameters, but nothing is showing in the player

![Screenshot 2024-06-25 174251](https://github.com/medcelerate/FFGLTouchEngine/assets/90050121/e284a584-17f7-4767-abec-486dd44d2ee9)
![Screenshot 2024-06-25 174913](https://github.com/medcelerate/FFGLTouchEngine/assets/90050121/0bcdfafe-8fa8-4b3a-8704-e4e0d285dccc)

**Comment by medcelerate** [comment]
I would not recommend building the entire solution. I would use the release builds available on github. FX is not in a release state. You also need at least a touchdesigner commercial license for it to work.

**Comment by phattiej** [comment]
Hey, thanks a lot, this is really awesome :)

The only thing is that I can only get the example tox files to load in the player. If I load my own tox files I can see the parameters but nothing shows in the output. I also have a commercial TD license.

**Comment by medcelerate** [comment]
There is a note in the readme at the bottom of how you have to name your output chop.

**Comment by phattiej** [comment]
yeaaah! thanks a lot! this is a huge game changer, my personal tox still isn't loading as I think my parameters are too complex, but the simpler ones are loading 😃

**Comment by medcelerate** [comment]
How many params do you have?

**Comment by phattiej** [comment]
Hey! actually I fixed it. I removed the absTime.seconds default parameter in TD, and also some dynamic color inputs. It seems the parameters only accepted for TouchEngine are float for now?
