### ISSUE TITLE
Parameter name in Resolume

### ISSUE THREAD

**Issue by j4s0n-c** [medcelerate/FFGLTouchEngine#6]
I think the parameter name that shows in Resolume should match the label property from TD, instead of the actual parameter name, since the label can have spaces and capital letters and other symbols.

**Comment by medcelerate** [comment]
Implemented Here: https://github.com/medcelerate/FFGLTouchEngine/commit/2bfbc50b5f5545d1061fd05c20d12e4ce17306ac
