### ISSUE TITLE
Linking Error with static Spout Library

### ISSUE THREAD

**Issue by j4s0n-c** [medcelerate/FFGLTouchEngine#7]
Hi. I get an error linking FFGLTouchEngine with the static Spout library (SpoutSenderNames.CreateSender()):

Error	LNK2001	unresolved external symbol "public: bool __cdecl spoutSenderNames::CreateSender(char const *,unsigned int,unsigned int,void *,unsigned long)" (?CreateSender@spoutSenderNames@@QEAA_NPEBDIIPEAXK@Z)	FFGLTouchEngine	<PATH>\FFGLTouchEngine-master\FFGLTouchEngine\TouchEngine.obj	1

Also, FYI: I had to add the solution's include library (`$(SolutionDir)include`) to the FFGLTouchEngineFX project's `Additional Include Directories` too in order to find the headers for GL/glew.h. I saw you had the folder included in the main project, but it wasn't included in FX.

**Comment by medcelerate** [comment]
I wouldn't recommend building from source at this time, there are a significant amount of changes and the build will fail for a number of reasons. I would either revert to a much older commit or use a release binary.

**Comment by medcelerate** [comment]
Latest versions build and link
